# 可以实现多个账号登录
network:
  -
    username: "xxxxxxxxxxx" # 联通手机号
    password: "xxxxxxxxxxx" # 密码，初始密码一般为123456
    wifi_is_open: true # 当前网络状态 WIFI: true  宽带: false
    wifi_name: "xxxxxxxxxxx" # 需登录的网络的WIFI名，需与联通手机号所在网络对应
  -
    username: "xxxxxxxxxxx"
    password: "xxxxxxxxxxx"
    wifi_is_open: true
    wifi_name: "xxxxxxxxxxx"

# 使用邮箱功能需到发送方的qq邮箱开启SMTP服务并获取授权码
# 通过邮箱发送日志
mail:
  is_open: false # true：开启发送邮箱的功能  false：关闭发送邮箱的功能
  sender_qq: "xxxxxxxxxxx" # 发送方的qq邮箱
  receiver_qq: # 接受方的qq邮箱，可以为多个邮箱
    - "xxxxxxxxxxx"
  sender_code: "xxxxxxxxxxx" # 发送方的授权码
