network:
  -
    username: "123456789"
    password: "123456"
    wifi_name: "123456"
  -
    username: "987654321"
    password: "123456"
    wifi_name: "只等妹妹"

mail:
  is_open: true
  sender_qq: "xxxxxxxx"
  receiver_qq:
    - "xxxxxxxx"
  sender_code: "xxxxxxxx"
