network:
  -
    username: "15676039902"
    password: "123456"
    wifi_name: "123456"
  -
    username: "15676036286"
    password: "123456"
    wifi_name: "只等妹妹"

mail:
  is_open: true
  sender_qq: "2324899362"
  receiver_qq:
    - "2223522114"
  sender_code: "dzxrccfdfeghebai"
